name: Scrape Grants

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pymongo python-dotenv lxml

      - name: Run nsw-grants.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python nsw-grants.py

      - name: Run grant-connect.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python grant-connect.py